import Head from "next/head";
import WhitePaper from "../components/whitePaper";

export default function Home() {
  return (
    <div className="bg-black">
      <Head>
        <title>HOODYGANG_WHITEPAPER</title>
        <meta name="description" content="Generated by Kilros" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <WhitePaper />
    </div>
  );
}
